name: First workflow
on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - master
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello GitHub Actions"
      - name: Print Goodbye!
        run: echo "{{ toJSON(gitHub.event)}}"
